# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=15, verbose_name='SCANNER')),
                ('start', models.TimeField(verbose_name='ON START')),
                ('end', models.TextField(verbose_name='FINSHED')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=5, verbose_name='METHOD')),
                ('host', models.CharField(max_length=40, verbose_name='HOST')),
                ('uri', models.CharField(default='/', max_length=100, verbose_name='FILE')),
                ('url', models.TextField(verbose_name='URL')),
                ('referer', models.TextField(verbose_name='REFERER')),
                ('data', models.TextField(verbose_name='REQUEST BODY')),
                ('cookie', models.TextField(default='', verbose_name='COOKIE')),
                ('scaned', models.BooleanField(default=False, verbose_name='BEEN SCANED')),
            ],
        ),
        migrations.CreateModel(
            name='vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vultype', models.CharField(default='', max_length=10, verbose_name='VULNER TYPE')),
                ('detail', models.TextField(default='', verbose_name='VULNER DETAIL')),
                ('assessmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chtscan.assessment')),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chtscan.request')),
            ],
        ),
    ]
