# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chtscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set([('method', 'host', 'uri')]),
        ),
    ]
