# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chtscan', '0003_auto_20160326_0426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set([]),
        ),
    ]
