# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chtscan', '0005_auto_20160408_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='requestid',
        ),
        migrations.AddField(
            model_name='assessment',
            name='requestid',
            field=models.IntegerField(null=True, verbose_name='REQUESTID'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='taskid',
            field=models.CharField(default='', max_length=50, verbose_name='TASKID'),
        ),
    ]
