# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chtscan', '0006_auto_20160411_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='taskid',
        ),
    ]
